.Environment.Name
rancher/rancher-compose-executor pull request #66
Opened 2017-07-16 04:52 UTC by carolynhu

2017-07-18 03:25 UTC, joshwget commented
Can you rebase this PR?

2017-07-25 05:54 UTC, joshwget commented
There's a bit or function reordering here that I'd rather avoid. Can we try to make it work without those changes?

2017-07-25 05:55 UTC, joshwget commented on project/context.go
> +	EnvName             string
Minor nit, can you change `Env` to `Environment` here and other places where it's shortened?

2017-07-25 22:24 UTC, joshwget commented on project/project.go
> +	// NewProject creates a new project with the specified context.
Can you move this back? It'll cause golint to complain.

2017-07-27 20:44 UTC, joshwget commented
LGTM

2017-08-02 23:15 UTC, cjellick commented
@carolynhu can you add an integration test for this change please?

2017-08-02 23:15 UTC, cjellick requested changes
@carolynhu can you add an integration test for this change please?

2017-08-03 21:01 UTC, joshwget commented
Test looks good.

2017-08-12 00:15 UTC, cjellick commented
LGTM

2017-08-12 00:16 UTC, cjellick approved these changes

2017-08-12 00:19 UTC, closed without merging

2017-08-14 16:51 UTC, cjellick commented
Replaced this with a PR that was for master branch